server:
  port: 0
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

logging:
  level:
    org.springframework.security: TRACE
    org.hibernate.SQL: DEBUG  # 显示 Hibernate 执行的 SQL 语句
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 显示绑定参数

spring:
  application:
    name: cas
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true   # 格式化 SQL 语句，便于阅读
        use_sql_comments: true # 在
        show_sql: true
  cache:
    type: redis #使用redis的cache抽象实现

  #profiles:
  # active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test-zerostart?useSSL=false&serverTimezone=UTC
    username: root
    password: 2005
  data:
    redis:
      password:
      port: 6379
      host: 127.0.0.1


  graphql:
    cors:
      allowed-origins: http://localhost:9000


  security:
    user:
      name: bili
      password: 1234

  mail:
    protocol: smtp
    host: smtp.qq.com
    port: 587
    username: 2897924003@qq.com
    password: ldqqcsrbgkufdgfe
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  rabbitmq:
    username: admin
    host: localhost
    password: admin
    port: 5672
    virtual-host: /


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka 服务端的地址
    register-with-eureka: true #将自己注册到注册中心，以便其他服务发现自己
  instance:
    hostname: localhost



